workflows:
  ios-build:
    name: iOS Build (no publish)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "ru.avocado.ios"
      groups:
        - keystore_credentials

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods

    scripts:
      # Очистка проекта
      - name: Clean Flutter project
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
          flutter pub get

      # Проверка среды
      - name: Check Flutter environment
        script: |
          flutter --version
          flutter doctor

      # Сборка iOS
      - name: Build iOS release
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/*.app
      - build/ios/archive/*.xcarchive

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
