name: constyle
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_downloader: 1.11.0

  # UI / UX
  cupertino_will_pop_scope: ^1.2.0
  wakelock_plus: ^1.2.5
  flutter_svg: ^2.0.10+1
  hexcolor: ^3.0.1
  mask_text_input_formatter: ^2.3.0

  # Firebase
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.0
  # firebase_core_platform_interface — НЕ нужен как прямой зависимый, тянется транзитивно

  # Notifications
  flutter_local_notifications: ^19.0.0

  # WebView / браузерные фичи
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.3.1

  # Медиа / сканеры
  audioplayers: ^6.1.0
  record_mp3_plus: ^1.3.0
  mobile_scanner: ^7.0.0-beta.1
  image_picker: ^1.1.2
  cached_network_image: ^3.2.1

  # Данные / сеть / хранилища
  http: 1.2.2
  dio: ^4.0.6
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  sqlite3: 2.9.0
  sqlite3_flutter_libs: 0.5.39
  package_info_plus: 8.1.0
  device_info_plus: any
  connectivity_plus: 4.0.0
  geolocator: 9.0.2

  # Система / разрешения / ID
  permission_handler: 11.4.0
  android_id: ^0.3.3

  # Прочее
  flutter_contacts: ^1.1.9+2
  uuid: 4.4.2
  get: ^4.6.5
  share_plus: 7.1.0
  flutter_widget_from_html: 0.16.0
  enough_convert: ^1.6.0
  flutter_exit_app: ^1.1.4

dependency_overrides:
  # Оставил только действительно полезные overrides.
  # Android-специфичные (image_picker_android, flutter_plugin_android_lifecycle, win32)
  # лучше НЕ оверрайдить без нужды — они иногда мешают резолву на iOS.
  platform: ^3.1.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
